### ISSUE TITLE
Running on ubuntu

### ISSUE THREAD

**Issue by stgleb** [Grazfather/BlackHatPython#1]
Hello, maybe this question may seems stupid.

But i am trying to run examples from chapter 3 on ubuntu using super user priveleges, it is got in stuck in 
raw_buffer = sniffer.recvfrom(65565)[0]

Maybe it is should be run under Linux Kali or there is another reason?

**Comment by Grazfather** [comment]
If it's stuck, it's probably just waiting. Make sure to ping your machine while the program is running.
